### ISSUE TITLE
[FEATURE] Universal warps

### ISSUE THREAD

**Issue by george112n** [BuildTheEarth/BuildTeamTools#17]
Have warps handled centrally across the entire network. A list of warps would be shared by every team on the network so a single /warp command would be able to access every team's warps.

This warp list could also be accessed via the universal navigator.

This was previously implemented in sledgehammer.

**Comment by george112n** [comment]
A database table for warps would be created. Each warp in the DB would have a country, some Minecraft coordinates, x, y, z, yaw and pitch.

**Comment by frikandelworst** [comment]
Perhaps we could integrate this into the website/polymap API? That way we could also display the warps on the map if we want to.

**Comment by george112n** [comment]
> Perhaps we could integrate this into the website/polymap API? That way we could also display the warps on the map if we want to.

Yeah that could be a good idea. I was considering storing the warp coordinates in latitude/longitude form so maybe we should do that to provide easier access to the warp list for external services.
